######################################################################
# Automatically generated by qmake (3.0) ?? 12? 30 23:49:14 2015
######################################################################

TEMPLATE = app
TARGET = qt_opencv
INCLUDEPATH += .
QT += widgets
qtHaveModule(printsupport): QT += printsupport

# Input
HEADERS += sliderwidget.h widget2.h detectcolor.h
SOURCES += main.cpp sliderwidget.cpp detectcolor.cpp widget2.cpp
