######################################################################
# Automatically generated by qmake (3.0) ?? 12? 10 17:29:03 2015
######################################################################

TEMPLATE = app
TARGET = qt_opencv
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += widget2.h sliderwidget.h
SOURCES += main.cpp widget2.cpp sliderwidget.cpp
